<section class="body">
    
    	    
    <form method="post" action="index/recibe">
    
        <label>Name</label>
        <input name="name" placeholder="Escribe aqu&iacute;" />
        
        <label>Email</label>
        <input name="email" type="email" placeholder="Escribe aqu&iacute;" />
        
        <label>Message</label>
        <textarea name="message" placeholder="Escribe aqu&iacute;"></textarea>
        
        <label>*What is 2+2? (Anti-spam)</label>
        <input name="human" placeholder="Escribe aqu&iacute;">        

        <input id="submit" name="submit" type="submit" value="Enviar" />
    
    </form>
    
</section>