<div class="right_panel">
	<header>
		<h1><a href="resume.html" class="title">paúl &nbsp;&nbsp;&nbsp;soberanes</a></h1>
	</header>
	<section>
		<p class="subtitle">{"web":"developer"}</p>
		<p class="speach">
			Hello! My name is <span>Pa&uacute;l Soberanes</span> and I am a passionate web developer based in Guadalajara, JAL, MX.<br />
			I would be very happy if you will contact me to work together on a project.<br />
			Do not be afraid and drop me an <a href="mailto:paul@paulsoberanes.com">e-mail</a> or contact me in any of the social networks.
		</p>
		<div class="social">
			<div id="facebook" class="icon"><a href="http://www.facebook.com/paaulsoberanes" >&nbsp;</a></div>
			<div id="twitter" class="icon"><a href="http://www.twitter.com/psoberanes_" >&nbsp;</a></div>
			<div id="linkedin" class="icon"><a href="http://mx.linkedin.com/pub/paul-alejandro-soberanes-osuna/28/460/792">&nbsp;</a></div>
			<div id="skype" class="icon"><a href="skype:paul.soberanes?call" >&nbsp;</a></div>
			<div id="instagram" class="icon"><a href="http://instagrid.me/paulsoberanes/">&nbsp;</a></div>
		</div>
	</section>
</div>
<div class="left_panel">
	<img src="<?= URL;?>/assets/style/images/paul.jpg" alt="paul_soberanes" class="img_paul" />
</div>
<div class="clearfix"></div>