<div class="right_panel">
	<header>
		<h1><a href="resume.html" class="title">paúl &nbsp;&nbsp;&nbsp;soberanes</a></h1>
	</header>
	<section>
		<p class="subtitle">{"web":"developer"}</p>
		<p class="speach">
			Hola! Mi nombre es <span>Pa&uacute;l Soberanes</span> y soy un apasionado desarrollador web que radica en Guadalajara, JAL, MX. <br />
			Estaría muy contento de colaborar contigo en alg&uacute;n proyecto, ser&iacute;a una valiosa experiencia para ambos.<br />
			Por favor si&eacute;ntete libre y cont&aacute;ctame por <a href="mailto:paul@paulsoberanes.com">mail</a> o por cualquiera de las redes sociales que aparecen abajo.
		</p>
		<div class="social">
			<div id="facebook" class="icon"><a href="http://www.facebook.com/paaulsoberanes" >&nbsp;</a></div>
			<div id="twitter" class="icon"><a href="http://www.twitter.com/psoberanes_" >&nbsp;</a></div>
			<div id="linkedin" class="icon"><a href="http://mx.linkedin.com/pub/paul-alejandro-soberanes-osuna/28/460/792">&nbsp;</a></div>
			<div id="skype" class="icon"><a href="skype:paul.soberanes?call" >&nbsp;</a></div>
			<div id="instagram" class="icon"><a href="http://instagrid.me/paulsoberanes/">&nbsp;</a></div>
			<div id="email" class="icon"><a href="contacto">Contacto</a></div>
		</div>
	</section>

</div>
<div class="left_panel">
	<img src="<?= URL;?>/assets/style/images/paul.jpg" alt="paul_soberanes" class="img_paul" />
</div>
<div class="clearfix"></div>